import type { Kashai } from '../types';

export const MOCK_KASHAI: Kashai[] = [
  {
    id: 'k1',
    name: 'মোহাম্মদ আলী',
    type: 'professional',
    area: 'মিরপুর-১০',
    district: 'ঢাকা',
    services: ['জবাই', 'সম্পূর্ণ কাটাকাটি', 'চামড়া ছাড়ানো', 'বাড়িতে সার্ভিস'],
    animals: ['গরু', 'মহিষ', 'ছাগল'],
    rateRange: '৳৩,০০০–৳৬,০০০/গরু',
    experience: '১৫ বছরের অভিজ্ঞতা',
    isHalalCertified: true,
    trustScore: 98,
    slotsAvailable: 3,
    isVerified: true,
    rating: 4.9,
    reviewCount: 127,
  },
  {
    id: 'k2',
    name: 'আবদুল করিম',
    type: 'professional',
    area: 'যাত্রাবাড়ী',
    district: 'ঢাকা',
    services: ['জবাই', 'সম্পূর্ণ কাটাকাটি', 'গ্রুপ কন্ট্র্যাক্ট'],
    animals: ['গরু', 'ছাগল', 'দুম্বা'],
    rateRange: '৳৪,০০০–৳৮,০০০/গরু',
    experience: '২০ বছরের অভিজ্ঞতা',
    isHalalCertified: true,
    trustScore: 97,
    slotsAvailable: 2,
    isVerified: true,
    rating: 4.8,
    reviewCount: 93,
  },
  {
    id: 'k3',
    name: 'রহিম উদ্দিন',
    type: 'day',
    area: 'উত্তরা',
    district: 'ঢাকা',
    services: ['জবাই', 'সম্পূর্ণ কাটাকাটি'],
    animals: ['গরু', 'ছাগল'],
    rateRange: '৳১,০০০–৳২,০০০/গরু',
    isHalalCertified: true,
    trustScore: 88,
    slotsAvailable: 5,
    isVerified: true,
    rating: 4.3,
    reviewCount: 21,
  },
  {
    id: 'k4',
    name: 'সালাউদ্দিন আহমেদ',
    type: 'professional',
    area: 'বহদ্দারহাট',
    district: 'চট্টগ্রাম',
    services: ['জবাই', 'সম্পূর্ণ কাটাকাটি', 'চামড়া ছাড়ানো', 'বাড়িতে সার্ভিস', 'গ্রুপ কন্ট্র্যাক্ট'],
    animals: ['গরু', 'মহিষ', 'ছাগল', 'দুম্বা'],
    rateRange: '৳৩,৫০০–৳৭,০০০/গরু',
    experience: '১২ বছরের অভিজ্ঞতা',
    isHalalCertified: true,
    trustScore: 96,
    slotsAvailable: 4,
    isVerified: true,
    rating: 4.7,
    reviewCount: 68,
  },
  {
    id: 'k5',
    name: 'মোঃ জহিরুল ইসলাম',
    type: 'day',
    area: 'খুলশী',
    district: 'চট্টগ্রাম',
    services: ['জবাই', 'সম্পূর্ণ কাটাকাটি'],
    animals: ['ছাগল', 'গরু'],
    rateRange: '৳৮০০–৳১,৫০০/গরু',
    isHalalCertified: false,
    trustScore: 82,
    slotsAvailable: 8,
    isVerified: false,
    rating: 4.1,
    reviewCount: 11,
  },
  {
    id: 'k6',
    name: 'নুরুল হক',
    type: 'professional',
    area: 'বন্দর',
    district: 'নারায়ণগঞ্জ',
    services: ['জবাই', 'সম্পূর্ণ কাটাকাটি', 'চামড়া ছাড়ানো'],
    animals: ['গরু', 'মহিষ'],
    rateRange: '৳২,৫০০–৳৫,০০০/গরু',
    experience: '৮ বছরের অভিজ্ঞতা',
    isHalalCertified: true,
    trustScore: 93,
    slotsAvailable: 6,
    isVerified: true,
    rating: 4.6,
    reviewCount: 44,
  },
  {
    id: 'k7',
    name: 'আরিফুল ইসলাম',
    type: 'day',
    area: 'মোহাম্মদপুর',
    district: 'ঢাকা',
    services: ['জবাই', 'সম্পূর্ণ কাটাকাটি'],
    animals: ['ছাগল', 'দুম্বা'],
    rateRange: '৳৫০০–৳১,২০০/ছাগল',
    isHalalCertified: true,
    trustScore: 85,
    slotsAvailable: 10,
    isVerified: true,
    rating: 4.2,
    reviewCount: 18,
  },
  {
    id: 'k8',
    name: 'হাফেজ আতাউল্লাহ',
    type: 'professional',
    area: 'রাজশাহী সদর',
    district: 'রাজশাহী',
    services: ['জবাই', 'সম্পূর্ণ কাটাকাটি', 'চামড়া ছাড়ানো', 'গ্রুপ কন্ট্র্যাক্ট'],
    animals: ['গরু', 'ছাগল', 'মহিষ'],
    rateRange: '৳২,০০০–৳৪,৫০০/গরু',
    experience: '১০ বছরের অভিজ্ঞতা',
    isHalalCertified: true,
    trustScore: 95,
    slotsAvailable: 3,
    isVerified: true,
    rating: 4.8,
    reviewCount: 56,
  },
  {
    id: 'k9',
    name: 'মকবুল হোসেন',
    type: 'day',
    area: 'ময়মনসিংহ সদর',
    district: 'ময়মনসিংহ',
    services: ['জবাই', 'সম্পূর্ণ কাটাকাটি'],
    animals: ['গরু', 'ছাগল'],
    rateRange: '৳৭০০–৳১,৫০০/গরু',
    isHalalCertified: false,
    trustScore: 79,
    slotsAvailable: 12,
    isVerified: false,
    rating: 3.9,
    reviewCount: 8,
  },
  {
    id: 'k10',
    name: 'ইলিয়াস আলী',
    type: 'professional',
    area: 'সিলেট সদর',
    district: 'সিলেট',
    services: ['জবাই', 'সম্পূর্ণ কাটাকাটি', 'চামড়া ছাড়ানো', 'বাড়িতে সার্ভিস'],
    animals: ['গরু', 'মহিষ', 'ছাগল', 'দুম্বা'],
    rateRange: '৳৩,০০০–৳৬,৫০০/গরু',
    experience: '১৮ বছরের অভিজ্ঞতা',
    isHalalCertified: true,
    trustScore: 99,
    slotsAvailable: 1,
    isVerified: true,
    rating: 5.0,
    reviewCount: 201,
  },
  {
    id: 'k11',
    name: 'ফারুক আহমেদ',
    type: 'day',
    area: 'খুলনা সদর',
    district: 'খুলনা',
    services: ['জবাই', 'সম্পূর্ণ কাটাকাটি'],
    animals: ['গরু', 'ছাগল'],
    rateRange: '৳৬০০–৳১,৩০০/গরু',
    isHalalCertified: true,
    trustScore: 84,
    slotsAvailable: 7,
    isVerified: true,
    rating: 4.0,
    reviewCount: 14,
  },
  {
    id: 'k12',
    name: 'আলমগীর হোসেন',
    type: 'professional',
    area: 'বরিশাল সদর',
    district: 'বরিশাল',
    services: ['জবাই', 'সম্পূর্ণ কাটাকাটি', 'চামড়া ছাড়ানো', 'গ্রুপ কন্ট্র্যাক্ট'],
    animals: ['গরু', 'মহিষ', 'ছাগল'],
    rateRange: '৳২,৫০০–৳৫,৫০০/গরু',
    experience: '৯ বছরের অভিজ্ঞতা',
    isHalalCertified: true,
    trustScore: 91,
    slotsAvailable: 5,
    isVerified: true,
    rating: 4.5,
    reviewCount: 37,
  },
];
